In [4]:
#Lab 4

Task 1  Part 1:  Initialise an array representing a uniformly distributed dataset containing 20 data points of integer type with minimum value 0 and maximum value 100. Visualise the values of the datapoints and plot the dataset.

In [5]:
#Libraries

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
S = np.array([10, 20, 50, 56, 99, 20, 99, 88, 10, 25, 45, 55, 72, 84, 31, 95, 8, 34, 27, 55])
S

array([10, 20, 50, 56, 99, 20, 99, 88, 10, 25, 45, 55, 72, 84, 31, 95,  8,
       34, 27, 55])

In [8]:
# Sort the array
NewS= np.sort(S)
# Display tenew array
print(NewS)

[ 8 10 10 20 20 25 27 31 34 45 50 55 55 56 72 84 88 95 99 99]


In [9]:
Mean = np.mean(S)
Median = np.median(S)
S1 = pd.Series(data=S)
Mode = S1.mode()
print('Mean:', Mean)
print('Median:', Median)
print('Mode:', Mode[0])

Mean: 49.15
Median: 47.5
Mode: 10


In [10]:
from scipy import stats as st

In [11]:
# Plot the dataset
plt.plot(S, marker='^', color='b')
# Add label
plt.ylabel('Data')
# Visualisethe plot
plt.show()

In [12]:
# Save the NumPy array as a pandasseries
S1 = pd.Series(data=S)
# Extract statistical data
D = S1.describe()
# Print statistical data
print(D.to_string())

count    20.000000
mean     49.150000
std      31.239777
min       8.000000
25%      23.750000
50%      47.500000
75%      75.000000
max      99.000000


Provide 2 different solutions for calculating the standard deviation:   Using a library function   Applying a formula without using a library function

In [13]:
#Lower quartile

In [14]:
# Calculating the interquartile range
print('Interquartile range: ', D[6] -D[4])

Interquartile range:  51.25


In [15]:
# Quartiles
Q1 = np.percentile(S, 25)
Q2 = np.median(S)
Q3 = np.percentile(S, 75)

# Interquartile Range (IQR)
IQR = Q3 - Q1

In [16]:
print("Lower Quartile (Q1):", Q1)
print("Median (Q2):", Q2)
print("Upper Quartile (Q3):", Q3)
print("Interquartile Range (IQR):", IQR)

Lower Quartile (Q1): 23.75
Median (Q2): 47.5
Upper Quartile (Q3): 75.0
Interquartile Range (IQR): 51.25


Initialise a two-dimensional array consisting of 5 rows and 10 columns of uniformly distributed data points of integer values from the interval [0..9]. Consider each row of the two-dimensional array as an independent dataset. Display the values on the screen as a table. Plot the first two rows on a single diagram with different colours.

In [17]:
import numpy as np
import matplotlib.pyplot as plt

# Create a 5x10 array of random integers between 0 and 9
data = np.random.randint(0, 10, size=(5, 10))

# Display the data as a table
print("Generated Data:")
print(data)

Generated Data:
[[1 2 8 8 2 0 5 0 4 5]
 [5 9 0 5 4 9 7 2 2 7]
 [7 9 1 5 2 4 5 1 9 0]
 [0 0 9 0 1 7 5 0 3 1]
 [8 4 0 7 8 0 6 9 5 9]]


Part 4 Find the maximum and the minimum values of the dataset and calculate the range.

In [18]:
print('Minimum value:', round(np.min(data),2))
print('Minimum value:', round(np.max(data),2))
print('Range:', round(np.max(data)-np.min(data),2))


Minimum value: 0
Minimum value: 9
Range: 9


5)Visualise the dataset by using a histogram with 10 bins. Visualise the probability density function.  Probability density function f: 𝒇= 𝟏 𝝈√𝟐𝝅𝒆−(𝑿−𝝁)𝟐 𝟐𝝈𝟐  Where X represents the data points, μ is the mean value and σ is the standard deviation

In [20]:
# Plot the histogram
A, X, C = plt.hist(data, bins=10, density=True)
# Calculate the probability density function
f = (1/(SD*np.sqrt(2*np.pi)))*np.exp(-((X-Mean)**2/(2*SD**2)))
# Plot the probability density function
plt.plot(X, f)
# Visualise the diagrams plt.show()

NameError: ignored